// <auto-generated />
using System;
using AppName.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppName.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702223401_AddBondValuationSnapshotAndRefreshState")]
    partial class AddBondValuationSnapshotAndRefreshState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AppName.Domain.Entities.BondValuationRefreshState", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastAsOf")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastAttemptDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BondValuationRefreshStates");
                });

            modelBuilder.Entity("AppName.Domain.Entities.BondValuationSnapshot", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AsOf")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BondPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConversionShares")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConversionValue")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsInTheMoney")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StockPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol");

                    b.ToTable("BondValuationSnapshots");
                });

            modelBuilder.Entity("AppName.Domain.Entities.ConvertibleBond", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConversionPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ParValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnderlyingSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol");

                    b.ToTable("ConvertibleBonds");
                });
#pragma warning restore 612, 618
        }
    }
}
