// <auto-generated />
using System;
using AppName.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppName.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppName.Domain.Entities.Bonds.BondValuationRefreshState", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("LastAsOf")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastAttemptDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("BondValuationRefreshStates");

                    b.HasData(
                        new
                        {
                            Id = 1L
                        });
                });

            modelBuilder.Entity("AppName.Domain.Entities.Bonds.BondValuationSnapshot", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<DateOnly>("AsOf")
                        .HasColumnType("date");

                    b.Property<decimal?>("BondPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ConversionShares")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ConversionValue")
                        .HasColumnType("numeric");

                    b.Property<bool?>("IsInTheMoney")
                        .HasColumnType("boolean");

                    b.Property<decimal>("StockPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Symbol");

                    b.ToTable("BondValuationSnapshots");
                });

            modelBuilder.Entity("AppName.Domain.Entities.Bonds.ConvertibleBond", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<decimal>("ConversionPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ParValue")
                        .HasColumnType("numeric");

                    b.Property<string>("UnderlyingSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Symbol");

                    b.ToTable("ConvertibleBonds");
                });
#pragma warning restore 612, 618
        }
    }
}
