/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestGridRouteImport } from './routes/test-grid'
import { Route as BondsRouteImport } from './routes/bonds'
import { Route as IndexRouteImport } from './routes/index'

const TestGridRoute = TestGridRouteImport.update({
  id: '/test-grid',
  path: '/test-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const BondsRoute = BondsRouteImport.update({
  id: '/bonds',
  path: '/bonds',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonds': typeof BondsRoute
  '/test-grid': typeof TestGridRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bonds': typeof BondsRoute
  '/test-grid': typeof TestGridRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bonds': typeof BondsRoute
  '/test-grid': typeof TestGridRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bonds' | '/test-grid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bonds' | '/test-grid'
  id: '__root__' | '/' | '/bonds' | '/test-grid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BondsRoute: typeof BondsRoute
  TestGridRoute: typeof TestGridRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-grid': {
      id: '/test-grid'
      path: '/test-grid'
      fullPath: '/test-grid'
      preLoaderRoute: typeof TestGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonds': {
      id: '/bonds'
      path: '/bonds'
      fullPath: '/bonds'
      preLoaderRoute: typeof BondsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BondsRoute: BondsRoute,
  TestGridRoute: TestGridRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
